version: '3'

services:
  app:
    environment:
      - BOT_TOKEN=5035451355:AAHIGWA3kvPZbBDbyRgkCLwQBDarKi_U1a0
      - CHAT_ID=1801701296
      - CHAT_ID2=1910993537
      - EMAIL=biel_surf159@hotmail.com
      - SENHA=130800Adry@
      - LOJA=@cremosinha
      - PORT=3001
      - HOST=ec2-15-229-7-92.sa-east-1.compute.amazonaws.com
    ports:
      - "80:3001"
    image: qzzdocker24/iphonebot:v1
      
    
